apiVersion: v1
kind: Service
metadata:
  name: my-demo-app-1
  labels:
    app: my-demo-app-1
spec:
  selector:
    app: my-demo-app-1
  ports:
    - port: 80
      name: http
  type: { { .Values.service.type } }
